version: '3'
services:
  backend_app:
    build: ./backend
    image: django-app
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/usr/app/backend
    depends_on:
      - db

  frontend_app:
    build: ./frontend
    image: react_app
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app/frontend
    depends_on:
      - backend_app

  db:
    image: mysql
    container_name: baza
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'