version: '3.9'
services:
  backend_app:
    build: ./backend
    image: django-app
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - /usr/app/backend
    networks:
      - app-network
    restart: always
    depends_on:
      db:
        condition: service_healthy

  frontend_app:
    build: ./frontend
    image: react_app
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/frontend
    networks:
      - app-network
    restart: always
    depends_on:
      backend_app:
        condition: service_started

  db:
    image: mysql
    container_name: baza
    ports:
      - "3306:3306"
    command: --init-file /usr/app/database/init.sql
    volumes:
      - ./init.sql:/usr/app/database/init.sql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge